### ISSUE TITLE
Use probably() only instead of decide()

### ISSUE THREAD

**Issue by lgeretti** [ariadne-cps/ariadne#150]
I am not at all sold by the choice of using decide() around for accepting LIKELY and TRUE. Since we have a probably(), we should stick to it. It is also more natural from a lexical viewpoint.

**Comment by lgeretti** [comment]
Right now decide() is used all over, where probably() is used only in hybrid_simulator.cpp and nonlinear_programming.cpp .

**Comment by pietercollins** [comment]
The rationale is that for algorithms which support both validated and approximate versions, 'decide' means "make an appropriate choice depending on the kind of information", whereas 'probably' is more specific as to the kind of choice wanted. Also, 'decide' works on effective logical types (reverting to a low-effort check).

I agree that the situation is not ideal. I also suspect that in some used, we want 'definitely' rather than 'probably' in the validated case. It would be useful to have a predicate which means "'definitely', except in the approximate case, in which just 'probably'". Maybe we could call this 'confidently', or maybe the clunkier 'definitely_or_probably' which may protect against misuse.

**Comment by lgeretti** [comment]
My perplexity comes from clauses like "if (decide(P))": are we expecting true or not true? At least "probably" suggests something. "decide" rather reads like "if I am able to give a definite answer, then true, otherwise false".
