### ISSUE TITLE
Solvers working with named variables

### ISSUE THREAD

**Issue by pietercollins** [ariadne-cps/ariadne#219]
What about using variable names for the non-hybrid case though? That would be a nice addition and it would make the interface consistent, even though we have two different classes. In that case, we may close this issue and make an appropriate enhancement one for that.

I don't understand: why avoid using named variables if the  kernel includes the symbolic module? Also, some symbolic manipulation is  sometimes necessary (e.g., checking if a function is constant or  additive in some variables, for differential inclusion function  manipulation purposes). Shouldn't we just use named variables at the  user layer (or at least provide both ways of interfacing), and indexed  variables internally? I guess this choice does not affect efficiency  significantly, while it offers a consistent user experience across  continuous and hybrid systems.

_Originally posted by @lgeretti in https://github.com/ariadne-cps/development/issues/206#issuecomment-424268866_

**Comment by pietercollins** [comment]
I want to keep the main kernel based on indexed variables (Vector) for efficiency. However, the Valuation, Expression and ExpressionSet classes provide named variables. In principle, they can replace Vector, Function and Set.

We do allow for named variables at the user layer, except that the Solver classes work with Function not Expression. We could (and at some point probably should) wrap the Solver classes. We will then also need to provide more conversions from numbered to named variables.

**Comment by lgeretti** [comment]
I still do not understand well what is the conclusion regarding this issue: shall we provide wrapping classes for the solver classes, in order to offer the symbolic functionality that users would definitely appreciate?

For example, some students of mine from last year were so unsatisfied with the plotting capabilities of Ariadne (release-1.0, but this is the same as the non-hybrid development code) that they just dumped the values and imported them into Matlab. We shall facilitate reading values within Ariadne.

**Comment by pietercollins** [comment]
In principle we should provide Solver classes on Valuations/Expressions, but let's think about how to do this first.
What did the students want to plot? If it's not related to the named-variable questions, please make a separate issue.
