### ISSUE TITLE
Simplify Integrator interface, decouple from Bounder

### ISSUE THREAD

**Issue by lgeretti** [ariadne-cps/ariadne#293]
I propose again to simplify the Integrator interface to only concern itself with the calculation of the flow function for a single step, where the flow bounds are supplied externally. This means removing `flow_to`, `flow`, `flow_bounds` and also the `flow_step` with no flow bounding.

The motivations are:

1. We end up never using multiple steps, in particular for hybrid evolution; bounding the flow on each step is preferable from an accuracy viewpoint (and the cost of finding the bounds is minor).
2. Bounding functionality is really orthogonal to integration, in particular:
3. There is a good case for multiple integrations on a given step based on common flow bounds. Example 1: for the Inclusion evolver it is preferable to check different integration schemes, namely varying the input approximation, while the flow bounds need to be computed only once. Example 2: refinement of input bounds when performing system decomposition requires to iterate integration, but the flow bounds are computed only once and then possibly refined.

**Comment by lgeretti** [comment]
Additionally, I think it might be worth having a `flow_step` for time-dependent dynamics with no parameters. In practice do have this option for Bounder, but Integrator currently assumes that if the dynamics are time-dependent, then the parameters box must also be provided.

**Comment by pietercollins** [comment]
I disagree. The main purpose of an `Integrator` is to compute the solution of a differential equation (by which we mean flow function, though we could also allow computing individual trajectories). So the *main* function is acutally `flow(f, X0, t0, tf, A)`, (though we could put the parameter domain argument `A` earlier). In principle, `flow_bounds` and the `flow_step`s are just the way in which all our implementations work.

One of the main reasons we don't use multiple steps is because we don't have a proper way of making a proper functions from the patches over  X0x[t0:t1]xA ∪ X0x[t1:t2]xA ∪ X2x[t1:t2]xA ∪ ... 
Of course, the step functions are useful in their own right. In some sense we should have a `FlowStepper` class to do this.

**Comment by lgeretti** [comment]
Therefore a further internal decoupling into a Bounder and a Stepper would be acceptable, but we don't want to drop the ability to compute flow on multiple steps or to decouple the Bounder. 

Well, when using multiple integration schemes (as in the DI Evolver) I guess I'll just compute the flow_bounds from any of the integrators. Doesn't make much sense to instantiate an n+1-th Bounder when I already got n Bounder objects within the integrators.
