### ISSUE TITLE
Distribute the hybrid module among the other modules

### ISSUE THREAD

**Issue by lgeretti** [ariadne-cps/ariadne#367]
Some time ago you suggested moving all hybrid classes into the corresponding modules. I agree with such move, would you do this @pietercollins or should I go with it myself?

**Comment by lgeretti** [comment]
Secondarily, do we want to split the "system" classes into their own module, or do we let all of them stay in the dynamics module?

**Comment by pietercollins** [comment]
I think it's at least worth splitting the hybrid module into submodules.

One thing I'm still a little unsure of is putting supporting functionality for hybrid systems together with the core functionality for Euclidean spaces. This is similar to objects like "expression sets" being in the `symbolic` module rather than `geometry` (and `Expression` being in `symbolic` and not `function`). Even more so, since most `hybrid` classes are geared to the solution of hybrid systems problems, which is quite a specific application domain compared to the generality of the core.

I think system classes should stay with classes for computing the dynamics.

**Comment by lgeretti** [comment]
Therefore it seems to me that we should either stay as we are, or distribute both the symbolic and hybrid modules as submodules to each core module.

**Comment by lgeretti** [comment]
Closed as won't fix.
